### ISSUE TITLE
Failing .go-solution on day05 after adding more test-data

### ISSUE THREAD

**Issue by Arxcis** [Arxcis/adventofcode2020#104]
When commiting 703e7f67a1a2d6152410d9d3e87e2d3e012a9ef6 I noticed a day05 solution started failing the tests:
![image](https://user-images.githubusercontent.com/3092618/102819933-aed11d80-43d4-11eb-9eed-015e4d115afe.png)
https://github.com/Arxcis/adventofcode2020/runs/1591237065

![image](https://user-images.githubusercontent.com/3092618/102819998-cad4bf00-43d4-11eb-9fb5-8ae2a4e0d7e3.png)
:thinking:

**Comment by Avokadoen** [comment]
This issue seems resolved! 👀

**Comment by Arxcis** [comment]
> This issue seems resolved! 👀

Ye because I disabled the solution. See:
https://github.com/Arxcis/adventofcode2020/blob/main/2020/day05/test.sh#L16-L17
