### ISSUE TITLE
Docker image size is getting too big

### ISSUE THREAD

**Issue by Arxcis** [Arxcis/adventofcode2020#126]
## Stats

After #125 - adding Kotlin support - the biggest layer is now 3.8GB!
```
[jonas@macbookpro adventofcode2020]$ make push
docker push "jonasjso/adventofcode2020:2021-12-04-with-kotlin-1.5.32"
The push refers to repository [docker.io/jonasjso/adventofcode2020]
23ad0c1ac26c: Pushing [==>                                                ]  213.3MB/3.8GB
```

But on [Dockerhub](https://hub.docker.com/repository/docker/jonasjso/adventofcode2020) it looks a bit smaller, still it is increasing in size
| 2020-12-18-with-zig-v0.7.1 | 2021-12-04-with-kotlin-1.5.32 |
|----|-------|
| ![image](https://user-images.githubusercontent.com/3092618/144757430-2f46ce2f-f439-41be-a57f-9e735f2d0f4e.png) | ![image](https://user-images.githubusercontent.com/3092618/144757415-92faa18b-25d9-4ab8-9a39-56f6ae3fa740.png) |

## Ideas on how to reduce size

Some ideas off the top of my head:
- Try to install more via `apt` if possible.
- Use a different distro than Ubuntu, with more packages available out of the box - maybe use Arch with Pacman + AUR instead?
- Install the things missing in `apt` from `brew` or `snap` instead - requires installing `brew` and `snap`. Not sure if this will reduce image size at all :thinking:

**Comment by Avokadoen** [comment]
Idea: Although not a direct solution, but maybe it would alleviate some of the pain to use some sort of sibling hierarchy. If you want to run all tests you communicate with the instance that will delegates to the zig, kotlin, go, etc .. -container. This way when a new update to one of the containers is applied then it will not produce an artifact containing GBs of data.

Of course this comes at the cost of execution time and project complexity ... 🤔

**Comment by Avokadoen** [comment]
github workflow even support this to some extent

**Comment by Avokadoen** [comment]
This could also solve #129 with a zig0.7.1 and a zig0.9-nigthly image

**Comment by Arxcis** [comment]
@Avokadoen Good idea 👏  Though I am a bit surprised/scared of the potential that the complexity of this project may spiral out of control 😆  I was not prepared for this when starting back in 2020 😅

**Comment by Arxcis** [comment]
Building on the discussion in this thread, and the one in #129, I am seeing two paths we could go down:
- Path 1: Make one Docker image per year.
- Path 2: Make one Docker image per language. (this requires that we run the tests language-by-language, instead of day-by-day like we do today)

~With Path 2, we also need images per year,  because the issue discussed in #129 will not go away. So we will potentially end up with a lot more docker images with path 2, as with path1 we are only producing 1 new image per year. The potential for Path 2 is, in worst case, to produce N new images per year, where N is the number of languages.~ **False claim, see comment below**

**Comment by Avokadoen** [comment]
I don't think path 2 would not require year based images if image is based on version as well as language like mentioned in my previous comment 🤔

**Comment by Arxcis** [comment]
> I don't think path 2 would not require year based images if image is based on version as well as language like mentioned in my previous comment 🤔

Fair point. Dockerhub will keep the history of images for a given language. And different solutions from different years may point to different versions of the same image. Aha! Ok. Then It is not as bad as I feared 😄

**Comment by Avokadoen** [comment]
Path 1 seems simpler like you mentioned and there would be no need to keep languages that are not used in the next year and vice versa which would help reduce image size

**Comment by Arxcis** [comment]
> Fair point. Dockerhub will keep the history of images for a given language. And different solutions from different years may point to different versions of the same image. Aha! Ok. Then It is not as bad as I feared 😄

By the way, doesn't this actually also solve #129 , because the 2020.yaml-workflow points to a specific tagged-version of our docker-image. We could just NOT update this tag in the 2020 workflow and thus updating zig to a newer version will in fact not break 2020 solutions, because the 2020-workflow use an older tag of our docker image... 🤔 While the 2021-workflow may use the newer tag! 🥳

**Comment by Avokadoen** [comment]
Stumbling on solutions is the best way to solve problems hahah

**Comment by Arxcis** [comment]
Docker image size much smaller after PR #138 :
![image](https://user-images.githubusercontent.com/3092618/145121427-42198464-3f68-4ee1-a515-8aab8df99241.png)
