### ISSUE TITLE
Question: Updating Zig will break CI for previous year?

### ISSUE THREAD

**Issue by Avokadoen** [Arxcis/adventofcode2020#129]
Zig has changed substantially since last year's 0.7.1

If the docker pulls zig-nightly it will probably break previous year CI, but I am guessing the CI does not run previous year?

**Comment by Arxcis** [comment]
CI does not pull nightly today. It pulls the specific version from last year, so all solutions from last year still work  ref: ![](https://github.com/Arxcis/adventofcode2020/workflows/2020/badge.svg)

https://github.com/Arxcis/adventofcode2020/blob/main/Dockerfile#L14

If you don't believe me (or the badge), run the workflow manually here -> https://github.com/Arxcis/adventofcode2020/actions/workflows/2020.yaml


**Will updating zig break last year?**

Yeah probably 😅 

**Here is a radical idea❗**

Create one Docker image per year:
- Allow different versions each year.
- Avoid breaking previous years when upgrading this year.

**Alternative**
- Just go back and fix ye olde code (but who wants to do that really realistically?)
- In 2025, do you want to go back to fix the 2020 code? Probably not
