### ISSUE TITLE
Which license should we have?

### ISSUE THREAD

**Issue by Arxcis** [Arxcis/adventofcode2020#16]
I have no idea. Github is suggesting to add a license everywhere. I am thinking the samller the better. MIT license perhaps. Does anyone have any feelings about this?

**Comment by Avokadoen** [comment]
I second MIT!

**Comment by Arxcis** [comment]
Well. We have 2 in favor of MIT, 0 agains. MIT it is :+1:

**Comment by Arxcis** [comment]
Unlicense https://unlicense.org/ :heart:

**Comment by Arxcis** [comment]
Closing this discussion. We are pushing for MIT in #53
