### ISSUE TITLE
Kill Java support?

### ISSUE THREAD

**Issue by Arxcis** [Arxcis/adventofcode2020#47]
- No-one is writing in Java at the moment.
- Java (openjdk-11) is a fat language-run-time which takes +200MB of the Docker image.
- Those 200MB could be used to have a smaller image, OR be freed up for people to add multiple smaller languages, if requested.

**Comment by tholok97** [comment]
👍 from me

**Comment by Arxcis** [comment]
I will wait a day or two, before executing, in case more opinions arise.

**Comment by Avokadoen** [comment]
Keep in mind this would be needed if we were to support scala or kotlin. I personally don't mind it being removed. 🤷‍♂️

**Comment by Arxcis** [comment]
Aww @Avokadoen . That is good input. It would be really cool to support Kotlin at some point... :thinking:

**Comment by Arxcis** [comment]
@Avokadoen your input was actually so good, that I want to close this issue for now :+1:
