### ISSUE TITLE
Make a benchmark with performance numbers for each day and language

### ISSUE THREAD

**Issue by Arxcis** [Arxcis/adventofcode2020#7]
**The Idea**
- Run a performance test across all days and all solutions, and generate a matrix comparing all result in a sexy manner, and publish to https://arxcis.github.io/adventofcode2020
- Remember to list and praise ALL contributors https://github.com/Arxcis/adventofcode2020/graphs/contributors.

**Comment by Avokadoen** [comment]
@Arxcis This can be closed?

**Comment by Arxcis** [comment]
Hmm. Yes :smile: It is! Not published on github.io. But we can scope-reduce :100:
