### ISSUE TITLE
Support clisp

### ISSUE THREAD

**Issue by Arxcis** [Arxcis/adventofcode2020#9]
Because @tholok97 wanted it
```
sudo apt install clisp
```

**Comment by Arxcis** [comment]
@tholok97 The way I see it, there is no rush to get this in, so I am leaving this issue as a intro-exercise for you. Sounds ok?

**Comment by tholok97** [comment]
> @tholok97 The way I see it, there is no rush to get this in, so I am leaving this issue as a intro-exercise for you. Sounds ok?

Sure 👍

**Comment by tholok97** [comment]
btw don't expect me to jump on this anytime soon. I need to learn ["hello world"](https://www.youtube.com/watch?v=-J_xL4IGhJA&ab_channel=MITOpenCourseWare) in the friggin thing first 😆

**Comment by Arxcis** [comment]
As stated, there is no rush. Leaving this issue open, but expectations are close to zero 👍 If you decide you dont want to do it at all, you are free to close.

**Comment by Arxcis** [comment]
Closing. Re-open if someone wants to do this eventually.
